apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "port-range-policy"
  namespace: "{{NS_NAME}}"
spec:
  description: "Allow traffic to a range of TCP ports"
  endpointSelector:
    matchLabels:
      app: api
  ingress:
  - toPorts:
    - ports:
      - port: "80"
        endPort: 444
        protocol: TCP
  
  # Allow ICMP for basic connectivity tests
  - icmps:
    - fields:
      - type: 8 # Echo Request (ping)
