apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "tcp-port-ingress-policy"
  namespace: "{{NS_NAME}}"
spec:
  description: "Allow TCP traffic to specific ports (L4 ingress policy)"
  endpointSelector:
    matchLabels:
      app: api
  ingress:
  - toPorts:
    - ports:
      - port: "80"
        protocol: TCP
      - port: "443"
        protocol: TCP
    fromEndpoints:
    - matchLabels:
        "k8s:io.kubernetes.pod.namespace": "{{NS_NAME}}"
  
  # Allow ICMP for basic connectivity tests
  - icmps:
    - fields:
      - type: 8 # Echo Request (ping)
