apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "basic-sni-policy"
  namespace: "{{NS_NAME}}"
spec:
  description: "Allow only TLS connections to specific domain (basic SNI policy)"
  endpointSelector:
    matchLabels:
      app: client
  egress:
  # Allow egress to specific domain via TLS SNI
  - toPorts:
    - ports:
      - port: "443"
        protocol: TCP
      serverNames:
      - "one.one.one.one"  # Allow connections only to one.one.one.one

  # Allow DNS resolution to function properly
  - toPorts:
    - ports:
      - port: "53"
        protocol: UDP
      - port: "53"
        protocol: TCP
    toEndpoints:
    - matchLabels:
        "k8s:io.kubernetes.pod.namespace": "kube-system"
        "k8s:k8s-app": "kube-dns"

  # Allow ICMP for basic connectivity testing
  - icmps:
    - fields:
      - type: 8  # Echo Request (ping)
