apiVersion: v1
kind: Pod
metadata:
  name: test-pod-1
  namespace: default
  labels:
    app: manual-test
spec:
  nodeName: mgmt-md-0-9nqt4-7h2qv
  containers:
  - name: netshoot
    image: nicolaka/netshoot
    command: ["sleep", "3600"]
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-2
  namespace: default
  labels:
    app: manual-test
spec:
  nodeName: mgmt-md-0-9nqt4-nfsvp
  containers:
  - name: netshoot
    image: nicolaka/netshoot
    command: ["sleep", "3600"]
  restartPolicy: Never
