apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "dns-matchname-policy"
spec:
  description: "Allow specific DNS queries using exact name matching"
  endpointSelector:
    matchLabels:
      app: client
  egress:
  - toEndpoints:
    - matchLabels:
        "k8s:io.kubernetes.pod.namespace": kube-system
        "k8s:k8s-app": kube-dns
    toPorts:
      - ports:
         - port: "53"
           protocol: ANY
        rules:
          dns:
            - matchName: "cilium.io"
            - matchName: "api.cilium.io"
            - matchName: "service1.api.cilium.io"
            # Add Kubernetes internal service entries
            - matchName: "kubernetes.default.svc.cluster.local"
            - matchName: "kube-dns.kube-system.svc.cluster.local"
