apiVersion: v1
kind: ConfigMap
metadata:
  name: cilium-config
  namespace: kube-system
data:
  # Enable DNS proxy to allow DNS-based policies
  enable-dns-proxy: "true"
  # Port range for transparent DNS proxy
  proxy-dns-port-range: "53:53"
