apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k8s-diagnostic-results-pvc
  namespace: k8s-diagnostic
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""

