apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "cidr-egress-policy"
  namespace: "{{NS_NAME}}"
spec:
  description: "Allow egress traffic from client2 to API pod via NODE1_CIDR"
  endpointSelector:
    matchLabels:
      app: client
      location: node2
  egress:
  # Allow traffic to the target pod's CIDR
  - toCIDR:
    - "{{NODE1_CIDR}}"
    toPorts:
    - ports:
      - port: "80"
        protocol: TCP
  # Allow traffic directly to the API pod
  - toEndpoints:
    - matchLabels:
        app: api
    toPorts:
    - ports:
      - port: "80"
        protocol: TCP
  # Allow ICMP for basic connectivity tests
  - toEndpoints:
    - matchLabels: {}
    icmps:
    - fields:
      - type: 8  # Echo Request (ping)
