apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: "l3-cidr-with-except"
spec:
  description: "Allow traffic from a CIDR block except for specific IPs"
  endpointSelector:
    matchLabels:
      app: web
  ingress:
  - fromCIDRSet:
    - cidr: "10.244.0.0/16"  # Allow pod network
      except:
      - "10.244.1.100/32"    # Except this specific IP
      - "10.244.2.0/24"      # Except this subnet
