apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "l3-node-policy"
  namespace: "{{NS_NAME}}"
spec:
  description: "Allow traffic from specific node only"
  endpointSelector:
    matchLabels:
      app: api
  ingress:
  # Allow all traffic from pods in the namespace (simpler approach)
  - fromEndpoints:
    - matchLabels:
        "k8s:io.kubernetes.pod.namespace": "{{NS_NAME}}"
    toPorts:
    - ports:
      - port: "80"
        protocol: TCP
  # Allow all traffic from the cluster (even more permissive)
  - fromEntities:
    - cluster
    toPorts:
    - ports:
      - port: "80"
        protocol: TCP
  # Allow ICMP for basic connectivity tests
  - icmps:
    - fields:
      - type: 8 # Echo Request (ping)
