apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "dns-based-policy"
  namespace: "{{NS_NAME}}"
spec:
  description: "Allow egress traffic to specific domain names"
  endpointSelector:
    matchLabels:
      app: client
  egress:
  # Allow DNS resolution (required for DNS-based policies to work)
  - toEndpoints:
    - matchLabels:
        "k8s:io.kubernetes.pod.namespace": kube-system
        "k8s:k8s-app": kube-dns
    toPorts:
    - ports:
      - port: "53"
        protocol: ANY  # Use ANY to cover both UDP and TCP
      rules:
        dns:
          - matchPattern: "*"  # Required L7 rule for DNS interception
  
  # Allow traffic to specific domain names
  - toFQDNs:
    - matchName: "example.com"  # Add plain example.com for the test
    - matchName: "api.example.com"
    - matchPattern: "*.api.example.com"
    - matchPattern: "*.example.com"  # Allow any subdomain of example.com
    toPorts:
    - ports:
      - port: "443"
        protocol: TCP
      - port: "80"
        protocol: TCP
  
  # Also allow ICMP for basic connectivity testing
  - toCIDR:
    - 0.0.0.0/0
    icmps:
    - fields:
      - type: 8 # Echo Request (ping)
