apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "endpoints-label-selector"
  namespace: "{{NS_NAME}}"
spec:
  description: "Allow traffic from endpoints with specific labels (endpoints-based policy)"
  endpointSelector:
    matchLabels:
      app: api
  ingress:
  # Allow traffic from pods in the namespace with specific labels
  - fromEndpoints:
    - matchLabels:
        "k8s:io.kubernetes.pod.namespace": "{{NS_NAME}}"
        app: client
    toPorts:
    - ports:
      - port: "80"
        protocol: TCP
  # Allow ICMP for basic connectivity tests
  - icmps:
    - fields:
      - type: 8 # Echo Request (ping)
